In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np


In [5]:
arr = np.array([1, 2, 3])
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])

In [4]:
np.zeros((3, 3))


array([[ 0.81466737, -0.80241027],
       [-1.02493559, -0.80684738],
       [-0.01337767,  0.58594027]])

In [23]:
np.ones((2, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.arange(0, 10, 2)


array([0, 2, 4, 6, 8])

In [26]:
np.linspace(0, 1, 5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
np.random.rand(3, 2)


array([[0.23899221, 0.30568015],
       [0.92328128, 0.69728147],
       [0.36809912, 0.90067586]])

In [21]:
np.random.randn(3, 2)

array([[ 0.72439688,  0.796376  ],
       [ 1.57604946,  1.57201441],
       [-0.4958978 , -0.80715811]])

In [5]:
arr = np.array([[1, 2, 3], [4, 5, 6]])


(2, 3)
2
6
int64


In [6]:
print(arr.shape)

(3,)


In [7]:
print(arr.ndim)

1


In [8]:
print(arr.size)

3


In [9]:
print(arr.dtype)

int64


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a + b

array([5, 7, 9])

In [12]:

a * b

array([ 4, 10, 18])

In [13]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [ ]:
print(arr.shape)


In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])


In [15]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [16]:
A @ B

array([[19, 22],
       [43, 50]])

In [18]:
arr = np.array([1, 2, 3, 4])
arr.sum()


np.int64(10)

In [19]:
arr.mean()


np.float64(2.5)

In [20]:
arr.max()


np.int64(4)

In [21]:
arr.min()


np.int64(1)

In [22]:
arr.std()

np.float64(1.118033988749895)

In [23]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]


np.int64(1)

In [24]:
arr[1:4]


array([2, 3, 4])

In [25]:
arr[::2]

array([1, 3, 5])

In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]


np.int64(2)

In [27]:
arr[:, 1]


array([2, 5])

In [28]:
arr[1, :2]

array([4, 5])

In [29]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3


In [30]:
arr[mask]

array([4, 5])

In [31]:
arr = np.arange(6)


In [32]:
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [33]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [34]:
np.vstack((a, b))


array([[1, 2],
       [3, 4]])

In [35]:
np.hstack((a, b))

array([1, 2, 3, 4])

In [17]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [19]:
np.save('array.npy', arr)


In [20]:
loaded_arr = np.load('array.npy&#39;)